sudo: required
services:
  - docker
before_install:
  - docker build -t muzeeburrahman/tele-prj -f Dockerfile.dev . 
script:
  - docker run muzeeburrahman/tele-prj:latest
after_success:
  - docker build -t muzeeburrahman/tele-prj . 
# Log in to Docker CLI to Push this Prod Image to DockerHub of muzeeburrahman.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push muzeeburrahman/tele-prj