FROM gradle:jdk11-slim as javabuild
USER root
WORKDIR /app
COPY ./ /app/
RUN gradle clean test jacocoTestCoverageVerification build --no-daemon --info

# Uncomment the below code To Run Docker Locally 
# FROM openjdk:11-jdk-slim
# WORKDIR /app
# COPY --from=javabuild /app/build/libs/app.jar /app/
# ENTRYPOINT ["java","-XX:MinRAMPercentage=50","-XX:MaxRAMPercentage=90","-XX:+PrintFlagsFinal","-jar","-Dserver.port=80","/app/app.jar"]
